# ==============================================================
# ENVIRONMENT: DEV
# ==============================================================

image:
  backend:
    tag: 8175f40
  frontend:
    tag: 8175f40

hpa:
  frontend:
    minReplicas: 1
  backend:
    minReplicas: 1

postgresql:
  primary:
    persistence:
      size: 10Gi
      storageClass: "gp3"

ingress:
  host: jerney.nilkanthprojects.site
  certificateArn: "arn:aws:acm:ap-south-1:310318659882:certificate/9144a150-f7ed-4286-8e3d-18e81950e4ee"
  groupName: jerney-platform

networkPolicy:
  vpcCidr: "10.0.0.0/16"
