# ==============================================================
# Jerney Helm Values — BASE (Shared Config)
# ==============================================================

image:
  backend:
    repository: docker.io/nmiyani/jerney-backend
  frontend:
    repository: docker.io/nmiyani/jerney-frontend

postgresql:
  enabled: true
  image:
    digest: "sha256:f60aa249d5be4ec1a9651ab05515f2eb9bb2b6eb664cd300abc19f13a208900d"
  auth:
    username: jerney_user
    database: jerney_db
    existingSecret: jerney-db-credentials
    secretKeys:
      adminPasswordKey: password
      userPasswordKey: password

service:
  frontend:
    type: ClusterIP
    port: 80
    targetPort: 8080
    annotations: {}
  backend:
    type: ClusterIP
    port: 5000
    targetPort: 5000
    annotations: {}
  db:
    type: ClusterIP
    port: 5432
    targetPort: 5432

hpa:
  frontend:
    maxReplicas: 10
    targetCPU: 50
  backend:
    maxReplicas: 10
    targetCPU: 50
