# ==============================================================
# ENVIRONMENT: PROD
# ==============================================================

image:
  backend:
    tag: 8175f40
  frontend:
    tag: 8175f40

hpa:
  frontend:
    minReplicas: 2
  backend:
    minReplicas: 2

postgresql:
  primary:
    persistence:
      size: 50Gi
      storageClass: "gp3"

ingress:
  host: jerney.nilkanthprojects.site
  certificateArn: "arn:aws:acm:ap-south-1:310318659882:certificate/9144a150-f7ed-4286-8e3d-18e81950e4ee"
  groupName: jerney-platform
  
networkPolicy:
  vpcCidr: "10.2.0.0/16"
