apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-apps.yaml
  - jerney.yaml
  - loki-stack.yaml
  - platform-config.yaml
  - platform-secrets.yaml
  - prometheus-stack.yaml
